---
version: 2
updates:
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '23:00'
  groups:
    python-packages:
      patterns:
      - "*"
