version: '3.8'

services:
  news_reader:
    image: ghcr.io/<your-github-username>/<repository-name>:latest
    container_name: news_reader
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY?Please set OPENAI_API_KEY environment variable}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - NEWS_READER_RSS=${NEWS_READER_RSS}
      - NEWS_READER_STATION_NAME=${NEWS_READER_STATION_NAME:-'News Update Radio'}
      - NEWS_READER_READER_NAME=${NEWS_READER_READER_NAME:-'OpenAI Shimmer'}
      - NEWS_READER_STATION_CITY=${NEWS_READER_STATION_CITY:-'Sydney'}
      - NEWS_READER_STATION_COUNTRY=${NEWS_READER_STATION_COUNTRY:-'Australia'}
      - NEWS_READER_TTS_VOICE=${NEWS_READER_TTS_VOICE:-'shimmer'}
      - NEWS_READER_TTS_QUALITY=${NEWS_READER_TTS_QUALITY:-'tts-1-hd'}
      - NEWS_READER_AUDIO_INTRO=${NEWS_READER_AUDIO_INTRO}
      - NEWS_READER_AUDIO_OUTRO=${NEWS_READER_AUDIO_OUTRO}
      - NEWS_READER_AUDIO_FIRST=${NEWS_READER_AUDIO_FIRST}
      - NEWS_READER_AUDIO_BREAK=${NEWS_READER_AUDIO_BREAK}
      - NEWS_READER_AUDIO_BED=${NEWS_READER_AUDIO_BED}
      - NEWS_READER_TIMEZONE=${NEWS_READER_TIMEZONE:-'Australia/Sydney'}
      - NEWS_READER_TIMING_INTRO=${NEWS_READER_TIMING_INTRO}
      - NEWS_READER_TIMING_OUTRO=${NEWS_READER_TIMING_OUTRO}
      - NEWS_READER_TIMING_BREAK=${NEWS_READER_TIMING_BREAK}
      - NEWS_READER_TIMING_FIRST=${NEWS_READER_TIMING_FIRST}
      - NEWS_READER_TIMING_BED=${NEWS_READER_TIMING_BED}
      - NEWS_READER_GAIN_BED=${NEWS_READER_GAIN_BED}
      - NEWS_READER_FADEIN_BED=${NEWS_READER_FADEIN_BED}
      - NEWS_READER_FADEOUT_BED=${NEWS_READER_FADEOUT_BED}
      - NEWS_READER_BOM_PRODUCT_ID=${NEWS_READER_BOM_PRODUCT_ID:-'IDN10064'}
      - OPENWEATHER_LAT=${OPENWEATHER_LAT:-'-33.8688'}
      - OPENWEATHER_LON=${OPENWEATHER_LON:-'151.2093'}
      - NEWS_READER_CRON=${NEWS_READER_CRON:-'*/15 * * * *'}
    volumes:
      - ./audio:/app/audio
    entrypoint: /app/src/main.py
